# config-repo/gateway.yml
server:
  port: 8080             # Cổng chạy Gateway

spring:
  application:
    name: gateway         # Tên ứng dụng đăng ký trên Eureka
  cloud:
    gateway:
      routes:
        - id: service-a-route
          uri: lb://service-a
          predicates:
            - Path=/service-a/**
          filters:
            - StripPrefix=1         # Loại bỏ phần "/service-a" trước khi forward
        - id: service-b-route
          uri: lb://service-b
          predicates:
            - Path=/service-b/**
          filters:
            - StripPrefix=1         # Loại bỏ phần "/service-a" trước khi forward

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL của Eureka Server
